from typing import Protocol, Optional, Dict, Any
from fastapi import WebSocket

class ILogger(Protocol):
    async def info(self, msg: str) -> None: ...
    async def error(self, msg: str) -> None: ...
    async def warning(self, msg: str) -> None: ...
    async def debug(self, msg: str) -> None: ...
    async def critical(self, msg: str) -> None: ...

class IDBHandler(Protocol):
    pass  # Define required DB methods as needed

class IWebSocketManager(Protocol):
    async def connect(self, websocket: WebSocket) -> None: ...
    async def disconnect(self, websocket: WebSocket) -> None: ...
    async def send_personal_message(self, data: str, websocket: WebSocket) -> None: ...
    async def send_info(self, websocket: WebSocket, content: str, source: str, session_id: Optional[str] = None, details: Optional[Dict[str, Any]] = None) -> None: ...
    async def send_warning(self, websocket: WebSocket, content: str, source: str, session_id: Optional[str] = None, details: Optional[Dict[str, Any]] = None) -> None: ...
    async def send_error(self, websocket: WebSocket, content: str, source: str, session_id: Optional[str] = None, details: Optional[Dict[str, Any]] = None) -> None: ...
    async def send_progress(self, websocket: WebSocket, content: str, source: str, progress: float, session_id: Optional[str] = None, details: Optional[Dict[str, Any]] = None) -> None: ...
    async def send_stage(self, websocket: WebSocket, content: str, source: str, session_id: Optional[str] = None, details: Optional[Dict[str, Any]] = None) -> None: ...
    async def send_result(self, websocket: WebSocket, content: str, source: str, session_id: Optional[str] = None, details: Optional[Dict[str, Any]] = None) -> None: ...
    async def send_debug(self, websocket: WebSocket, content: str, source: str, session_id: Optional[str] = None, details: Optional[Dict[str, Any]] = None) -> None: ...
    async def broadcast(self, message: str) -> None: ...
    async def broadcast_json(self, msg: Dict[str, Any]) -> None: ...
    async def broadcast_standard(self, *, type: str, source: str, content: str, session_id: Optional[str] = None, progress: Optional[float] = None, details: Optional[Dict[str, Any]] = None) -> None: ...
