from typing import Protocol
from fastapi import WebSocket

class ILogger(Protocol):
    async def info(self, msg: str) -> None: ...
    async def error(self, msg: str) -> None: ...
    async def warning(self, msg: str) -> None: ...
    async def debug(self, msg: str) -> None: ...
    async def critical(self, msg: str) -> None: ...

class IDBHandler(Protocol):
    pass  # Define required DB methods as needed

class IWebSocketManager(Protocol):
    async def connect(self, websocket: WebSocket) -> None: ...
    async def disconnect(self, websocket: WebSocket) -> None: ...
    async def send_personal_message(self, data: str, websocket: WebSocket) -> None: ...
